apiVersion: v1
kind: List
metadata:
items:
- kind: Deployment
  apiVersion: apps/v1 
  metadata:
    labels:
      app: aetos
    name: aetos
  spec:
    selector:
      matchLabels:
        app: aetos
    template:
      metadata:
        labels:
          app: aetos
      spec:
        containers:
        - command:
          - --cardinality=3
          - --labels=3
          - --metrics=3
          image: localhost:32000/aetos:649abbe66bdbffbd0f4b8c751a6475f9e9de2c76
          imagePullPolicy: IfNotPresent
          name: aetos
          ports:
          - name: metrics
            containerPort: 8080
            protocol: TCP
          resources: {}
- kind: Service
  apiVersion: v1
  metadata:
    labels:
      app: aetos
    name: aetos
  spec:
    selector:
      app: aetos
    ports:
    - port: 8080
      protocol: TCP
      targetPort: metric
    type: NodePort
- kind: ServiceMonitor
  apiVersion: monitoring.coreos.com/v1
  metadata:
    labels:
      app: aetos
    name: aetos
  spec:
    selector:
      matchLabels:
        app: aetos
    endpoints:
    - interval: 15s
      port: 8080
