// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.25.2
// source: aetos.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AetosPublishRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Labels  []string `protobuf:"bytes,2,rep,name=labels,proto3" json:"labels,omitempty"`
	Metrics []string `protobuf:"bytes,3,rep,name=metrics,proto3" json:"metrics,omitempty"`
}

func (x *AetosPublishRequest) Reset() {
	*x = AetosPublishRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aetos_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AetosPublishRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AetosPublishRequest) ProtoMessage() {}

func (x *AetosPublishRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aetos_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AetosPublishRequest.ProtoReflect.Descriptor instead.
func (*AetosPublishRequest) Descriptor() ([]byte, []int) {
	return file_aetos_proto_rawDescGZIP(), []int{0}
}

func (x *AetosPublishRequest) GetLabels() []string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *AetosPublishRequest) GetMetrics() []string {
	if x != nil {
		return x.Metrics
	}
	return nil
}

type AetosPublishResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AetosPublishResponse) Reset() {
	*x = AetosPublishResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aetos_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AetosPublishResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AetosPublishResponse) ProtoMessage() {}

func (x *AetosPublishResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aetos_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AetosPublishResponse.ProtoReflect.Descriptor instead.
func (*AetosPublishResponse) Descriptor() ([]byte, []int) {
	return file_aetos_proto_rawDescGZIP(), []int{1}
}

var File_aetos_proto protoreflect.FileDescriptor

var file_aetos_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x61, 0x65, 0x74, 0x6f, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x16, 0x63,
	0x6f, 0x6d, 0x2e, 0x64, 0x61, 0x7a, 0x77, 0x69, 0x6c, 0x6b, 0x69, 0x6e, 0x2e, 0x61, 0x65, 0x74,
	0x6f, 0x73, 0x2e, 0x76, 0x31, 0x22, 0x47, 0x0a, 0x13, 0x41, 0x65, 0x74, 0x6f, 0x73, 0x50, 0x75,
	0x62, 0x6c, 0x69, 0x73, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06,
	0x6c, 0x61, 0x62, 0x65, 0x6c, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x6c, 0x61,
	0x62, 0x65, 0x6c, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x18,
	0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x22, 0x16,
	0x0a, 0x14, 0x41, 0x65, 0x74, 0x6f, 0x73, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0x6d, 0x0a, 0x05, 0x41, 0x65, 0x74, 0x6f, 0x73, 0x12,
	0x64, 0x0a, 0x07, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x12, 0x2b, 0x2e, 0x63, 0x6f, 0x6d,
	0x2e, 0x64, 0x61, 0x7a, 0x77, 0x69, 0x6c, 0x6b, 0x69, 0x6e, 0x2e, 0x61, 0x65, 0x74, 0x6f, 0x73,
	0x2e, 0x76, 0x31, 0x2e, 0x41, 0x65, 0x74, 0x6f, 0x73, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2c, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x64, 0x61,
	0x7a, 0x77, 0x69, 0x6c, 0x6b, 0x69, 0x6e, 0x2e, 0x61, 0x65, 0x74, 0x6f, 0x73, 0x2e, 0x76, 0x31,
	0x2e, 0x41, 0x65, 0x74, 0x6f, 0x73, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x23, 0x5a, 0x21, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x44, 0x61, 0x7a, 0x57, 0x69, 0x6c, 0x6b, 0x69, 0x6e, 0x2f, 0x41, 0x65,
	0x74, 0x6f, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_aetos_proto_rawDescOnce sync.Once
	file_aetos_proto_rawDescData = file_aetos_proto_rawDesc
)

func file_aetos_proto_rawDescGZIP() []byte {
	file_aetos_proto_rawDescOnce.Do(func() {
		file_aetos_proto_rawDescData = protoimpl.X.CompressGZIP(file_aetos_proto_rawDescData)
	})
	return file_aetos_proto_rawDescData
}

var file_aetos_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_aetos_proto_goTypes = []interface{}{
	(*AetosPublishRequest)(nil),  // 0: com.dazwilkin.aetos.v1.AetosPublishRequest
	(*AetosPublishResponse)(nil), // 1: com.dazwilkin.aetos.v1.AetosPublishResponse
}
var file_aetos_proto_depIdxs = []int32{
	0, // 0: com.dazwilkin.aetos.v1.Aetos.Publish:input_type -> com.dazwilkin.aetos.v1.AetosPublishRequest
	1, // 1: com.dazwilkin.aetos.v1.Aetos.Publish:output_type -> com.dazwilkin.aetos.v1.AetosPublishResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_aetos_proto_init() }
func file_aetos_proto_init() {
	if File_aetos_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_aetos_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AetosPublishRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_aetos_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AetosPublishResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_aetos_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_aetos_proto_goTypes,
		DependencyIndexes: file_aetos_proto_depIdxs,
		MessageInfos:      file_aetos_proto_msgTypes,
	}.Build()
	File_aetos_proto = out.File
	file_aetos_proto_rawDesc = nil
	file_aetos_proto_goTypes = nil
	file_aetos_proto_depIdxs = nil
}
